name: Build Chatup App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [android, ios, macos, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore Chatup.sln

      - name: Build
        run: dotnet build Chatup.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Chatup.App/Chatup.App.csproj -c Release -o ./output/${{ matrix.platform }} --self-contained --runtime ${{ matrix.platform }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-build
          path: ./output/${{ matrix.platform }}