name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'

      - name: Restore dependencies
        run: dotnet restore Chatup.Backend/Chatup.Backend.csproj

      - name: Build
        run: dotnet build Chatup.Backend/Chatup.Backend.csproj --configuration Release

      - name: Publish
        run: dotnet publish Chatup.Backend/Chatup.Backend.csproj --configuration Release --output ./publish

      - name: Deploy to Google Cloud
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo $GCP_SA_KEY | base64 --decode > gcloud-key.json
          gcloud auth activate-service-account --key-file gcloud-key.json
          gcloud config set project $GCP_PROJECT_ID
          gcloud app deploy ./publish --quiet